import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  function getRandomInt(min: number, max: number) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min) + min);
  }

  const colours = ["#ff7b72", "#79c0ff", "#a5d6ff", "#d2a8ff", "#7ee787"];

  const codeBlocks = (): Array<JSX.Element> =>
    Array.from(Array(getRandomInt(12, 28)).keys()).map((_, i) => {
      return (
        <div
          key={i}
          className={styles.codeblock}
          style={{
            backgroundColor: colours[getRandomInt(0, colours.length)],
            width: `${getRandomInt(10, 100)}%`,
          }}
        ></div>
      );
    });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.headercontainer}>
          <h1 className={inter.className} style={{ position: 'absolute', zIndex: 20, fontSize: '4rem', textShadow: '3px 3px 1px rgba(77,77,77,0.5)' }}>
            Jacob Robinson
            <br />
            <span className={styles.subtitle}>Full Stack Developer</span>
          </h1>
          <div className={styles.perspectivebox}>
            <div className={styles.boxinner}>{codeBlocks()}</div>
          </div>
        </div>
      </main>
    </>
  );
}
